### ISSUE TITLE
Hello, can you share me your pytorch code, I want to understand and analysis your paper ? Thanks !   My personal email is : 1228436902@qq.com

### ISSUE THREAD

**Issue by shuyuandeqipa** [HaohanWang/HFC#1]

**Comment by jiaming-lee** [comment]
Me too, I would appreciate it if the author could share the pytorch code and my email is ljmd@mail.ustc.edu.cn.

**Comment by HaohanWang** [comment]
PyTorch implementation can be downloaded here now: https://github.com/HaohanWang/HFC/blob/master/pytorch_implementation.zip
